### ISSUE TITLE
Peer to peer code review, 1 April 2021

### ISSUE THREAD

**Issue by tiagorahal** [pountzas/TicTacToe-with-Rspec#2]
* # Suggestions:
  * ## Finish the project.

**Comment by pountzas** [comment]
thank you for your suggestions!! match appreciated you saved my life.

**Comment by pountzas** [comment]
Project Completed.

**Comment by tiagorahal** [comment]
![Congratulations](https://media.giphy.com/media/bKBM7H63PIykM/giphy.gif)
